version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: tiktok-ads-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: tiktok_user
      POSTGRES_PASSWORD: tiktok_pass
      POSTGRES_DB: tiktok_ads_automation
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U tiktok_user -d tiktok_ads_automation']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tiktok-ads-network

  # Redis Cache & Queue
  redis:
    image: redis:7-alpine
    container_name: tiktok-ads-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tiktok-ads-network

  # Prisma Studio (Database GUI)
  prisma-studio:
    image: node:18-alpine
    container_name: tiktok-ads-prisma-studio
    working_dir: /app
    command: sh -c "npm install -g prisma && npx prisma studio"
    ports:
      - '5555:5555'
    environment:
      DATABASE_URL: postgresql://tiktok_user:tiktok_pass@postgres:5432/tiktok_ads_automation
    volumes:
      - ./apps/backend/prisma:/app/prisma
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - tiktok-ads-network
    profiles:
      - tools

  # Redis Commander (Redis GUI)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: tiktok-ads-redis-commander
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      REDIS_HOSTS: local:redis:6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - tiktok-ads-network
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  tiktok-ads-network:
    driver: bridge
